config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/login' => 'session#new'
 post '/login' => 'session#create'
 delete '/login' => 'session#destroy'

 resources :users
  resources :customers



  resources :accounts do
    resources :transactions
  end

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user, optional: true
  # has_many :transactions
  has_many :from_transactions, class_name: 'Transaction', foreign_key: :from_account_id
  has_many :to_transactions,   class_name: 'Transaction', foreign_key: :to_account_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # has_one :account , as: "from"
  # has_one :account , as: "to"


  # has_one :account , :class_name => 'Account' , :foreign_key => :from_account_id
  # has_one :account , :class_name => 'Account' , :foreign_key => :to_account_id

  belongs_to :from_account , class_name: 'Account', optional: true
  belongs_to :to_account , class_name: 'Account', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :customer
  has_many :accounts
  has_many :from_transactions, through: :accounts
  has_many :to_transactions, through: :accounts


  def all_transactions
    self.from_transactions + self.to_transactions
  end

  has_secure_password

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :check_if_logged_in

  def home
  end

  # CREATE

  def new
    # blank form
    @account = Account.new
  end



  # READ

  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find params[:id]

  end


  # UPDATE

  def edit
    @account = Account.find params[:id]
  end


  def create
    user = User.find_by( id: params[:user_id] )
    account = Account.new account_params
    account.date_opened = DateTime.now
    characters = ('a'..'z').to_a + (0..9).to_a + (0..9).to_a + (0..9).to_a
    char = characters.sample 10
    account.accountnumber = char.join
    account.user = @current_user
    account.save
    redirect_to @current_user


  end

  # def update
  #   account = Account.find params[:id]
  #   account.update account_params
  #   redirect_to account
  # end

  def destroy
    Account.destroy params[:id]
    redirect_to accounts_path
  end

  private

  # "strong params" for the work form submit - only let through the fields
  # which we expect (i.e. the table fields the user is allowed to edit)
  def account_params
    params.require(:account).permit( :accountnumber, :user_id, :balance, :account_type  )
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user

  def check_if_logged_in
    if @current_user.nil?
      flash[:error] = "You must be logged in to view this page."
      redirect_to login_path
    end
  end

  def check_if_admin
    unless @current_user.present? && @current_user.is_admin?
      flash[:error] = "You must be an admin to view this page."
      redirect_to login_path
    end
  end

  private
  def fetch_user

    # Retrieve the currently-logged-in user's data from the database
    # (if they are actually logged in)
    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    # On the off change the session user ID does not exist in the
    # database (i.e. we have re-seeded the 'users' table), delete the session
    session[:user_id] = nil unless @current_user.present?
  end



end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  # before_action :check_if_logged_in

  def home
  end

  # CREATE

  def new
    # blank form
    @customer = Customer.new
  end



  # READ

  def index
    @customers = Customer.all
  end

  def show
    @customer = @current_user.customer

  end


  # UPDATE

  def edit
    @customer = @current_user.customer
  end


  def create
    user = User.find_by( id: params[:user_id] )
    customer = Customer.new customer_params

    customer.user = @current_user
    customer.save
    redirect_to @current_user


  end

  def update
    customer = @current_user.customer
    customer.update customer_params
    redirect_to customer_path
  end

  # def destroy
  #   Cus.destroy params[:id]
  #   redirect_to accounts_path
  # end

  private

  # "strong params" for the work form submit - only let through the fields
  # which we expect (i.e. the table fields the user is allowed to edit)
  def customer_params
    params.require(:customer).permit( :first_name, :last_name, :user_id, :address, :phone_number  )
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.all
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by email: params[:email]


    if user.present? && user.authenticate(params[:password])
      # successful login
      # create a cookie to store a session, and keep track of the user ID
      session[:user_id] = user.id
      redirect_to user_path user
    else
      # bad credentials/unsuccessful login
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :check_if_logged_in

  def index
    @transactions = Transaction.all
  end

  def show
  @transaction = Transaction.find params[:id]
  end

  def new
    @transaction = Transaction.new
    @account = Account.find params[:account_id]

    # if params[:type] == 'from'
    #
    # else
    #   # assume it's "to"
    # end
    #
  end


    def create
      # form submits here

      account = Account.find_by( id: params[:account_id] )

      if account.present?

        # make sure the account belongs to the logged-in user
        redirect_to root_path unless account.user = @current_user

        transaction = Transaction.create transaction_params


        transaction.date_opened = DateTime.now
          # raise 'hell'
          transaction.save




        if transaction.persisted?




          transaction.from_account.decrement!('balance' , transaction[:ammount])
          transaction.to_account.increment!('balance' , transaction[:ammount])






           # raise 'hell'

          # add/subtract the amount FROM the from_account_id, and ADD it to
          # the to_account_id
          # transaction.from_account.update balance:

          redirect_to account

        else
          # validation error?
          flash[:errors] = transaction.errors.full_messages
          redirect_to new_account_transaction_path( account )
        end
      else
        # account not found
        redirect_to @current_user
      end


    end


private

# "strong params" for the work form submit - only let through the fields
# which we expect (i.e. the table fields the user is allowed to edit)
def transaction_params
  params.require(:transaction).permit( :ammount, :from_account_id, :to_account_id, :description, :from_account_date_opened, :to_account_date_opened )
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    if user.persisted?
      # user successfully created, redirect to profile page for this user
      session[:user_id] = user.id
      # redirect_to user_path user
      redirect_to new_customer_path
    else
      # error creating user (probably a validation error)
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find params[:id]

  end

  def edit
    @user = User.find params[:id]
  end

  def update
  end



  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<br>
<br>
<%= form_for @account do |f| %>


  <fieldset>
    <%= f.label :balance %>
    <%= f.text_field :balance, :class => "form-control" %>
  </fieldset>

  <fieldset>
    <%= f.label :account_type %>
    <%= f.text_field :account_type, :class => "form-control" %>
  </fieldset>
  <br>

  <%= f.submit %>

<% end %>

app/views/accounts/edit.html.erb
<%= render partial: 'form' %>

app/views/accounts/home.html.erb
<h2>Accounts</h2>

app/views/accounts/index.html.erb
<h2>All Accounts</h2>

<ul>
  <% @accounts.each do |account| %>

    <li>
      <em><%= link_to account.accountnumber, account_path( account ) %></em>

      , <%= account.account_type %>
    </li>

  <% end %>
</ul>

app/views/accounts/new.html.erb
<%= render partial: 'form' %>

app/views/accounts/show.html.erb
<br>
<hr>




</div>
<h4>Account Information</h4>
<hr>
<div class="col-xs-12 col-md-8">
<p class="bg-danger">Account number: <%= @account.accountnumber %></p>
<p class="bg-danger">Account Type: <%= @account.account_type %></p>
<p class="bg-danger">Current Balance: <%= @account.balance %>$</p>
<p class="bg-danger">Account Created on : <%= @account.date_opened %></p>




<br>
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Transfer Funds
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <div id = "fund">
<%= link_to 'Withdraw', new_account_transaction_path( @account, type: :from ) %>

<hr>

<%= link_to 'Desposit', new_account_transaction_path( @account, type: :to ) %>
</div>
</ul>
</div>

<hr>






<button data-toggle="collapse" data-target="#demo">Transaction History</button>

<div id="demo" class="collapse">

<hr>
<h5>From Transactions: </h5>
<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search" >

<table id="myTable">
  <tr class="header">
    <th style="width:60%;">Date</th>
    <th style="width:40%;">Amount</th>
    <th style="width:40%;">Description</th>
  </tr>
<% @account.from_transactions.each do |transaction| %>



  <tr>
   <td><%= transaction.date_opened %></td> <td><%= transaction.ammount %>$</td>   <td><%= transaction.description %></td>


    <% end %>
  </tr>
 </table>
    <hr>


     <%= area_chart @account.from_transactions.group(:date_opened).maximum(:ammount) %>


<br>
<hr>
<h5>To Transactions: </h5>
<%#= line_chart Account.group_by_day(:created_at).count %>
<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search" >

<table id="myTable">
  <tr class="header">
    <th style="width:60%;">Date</th>
    <th style="width:40%;">Amount</th>
    <th style="width:40%;">Description</th>
  </tr>

<% @account.to_transactions.each do |transaction| %>

<tr>
  <td> <%= transaction.date_opened %></td>  <td><%= transaction.ammount %>$</td>   <td><%= transaction.description %> </td>

    <% end %>
  </tr>
 </table>
    <hr>

    <%= area_chart @account.to_transactions.group(:date_opened).maximum(:ammount) %>

</div>

</div>




<%#= link_to 'Delete Account', account_path , method: 'delete' %>

app/views/customers/_form.html.erb
<% if flash[:errors] %>
  <strong>Please correct the following errors:</strong>
  <ol>
  <% flash[:errors].each do |e| %>
    <li><%= e %></li>
  <% end %>
  </ol>
<% end %>

<%= form_for @customer do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name, :class => "form-control" %>
<br>
<%= f.label :last_name %>
<%= f.text_field :last_name, :class => "form-control" %>
<br>
<%= f.label :address %>
<%= f.text_field :address, :class => "form-control" %>
<br>
<%= f.label :phone_number %>
<%= f.text_field :phone_number, :class => "form-control" %>
<br>
<%= f.submit %>

<% end %>

app/views/customers/edit.html.erb
<h2>Edit your personal Information</h2>

<%= render partial: 'form' %>

app/views/customers/new.html.erb
<h4>You are just one step away from creating your account</h4>

<%= render partial: 'form' %>

app/views/customers/show.html.erb
<br>
<br>
<div class = "customer">
<p>First Name:<%= @customer.first_name %></p>
<p>Last Name: <%= @customer.last_name %></p>
<p>Address: <%= @customer.address %></p>
<p>Contact Number: <%= @customer.phone_number %></p>

<%= link_to 'Edit Details', edit_customer_path %>
</div>

app/views/home/index.html.erb
<div class="container-fluid text-center bg-grey">
  <br>

  <h4>Here is what we have created</h4>
  <div class="row text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://www.acrobatremovals.com/wp-content/uploads/2015/03/o-save-money-facebook.jpg" alt="Paris">
        <p><strong>Need to start Saving?</strong></p>
        <p>Our bank can help to reach your goal sooner</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://www.chill.ie/images/insurance-news/large/travelling-this-summer-l.jpg" alt="New York">
        <p><strong>Travelling Soon?</strong></p>
        <p>Get a travel money card</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://www.achieveunite.com/wp-content/uploads/2017/06/Business-Ready.jpg" alt="San Francisco">
        <p><strong>Getting Buisness ready?</strong></p>
        <p>Quick tips on how we can help you manage our buisness</p>
      </div>
    </div>
</div>

<h2>What our customers say</h2>
<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <h4>"This bank is the best. I am so happy with the service!"<br><span style="font-style:normal;">Michael Roe</span></h4>
    </div>
    <div class="item">
      <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
    </div>
    <div class="item">
      <h4>"Could I... BE any more happy with the service they offer?"<br><span style="font-style:normal;">Joe</span></h4>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineBank</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= cloudinary_js_config %>


  </head>

  <body>
    <div class="container">
      <header class = "main">

    <h2>Sydney Bank</h2>

     <% if @current_user.present? %>
     <nav>

        <%= link_to @current_user.name , @current_user %>
        |
        <%= link_to 'Logout', login_path, method: :delete %>
     <% else %>
     <div class="link">
       <%= link_to 'Login', login_path %>
       |


        <%= link_to 'SignUp', new_user_path %>
        </div>
        </nav>


     <% end %>
     </header>




    <%= yield %>

    <br>

    <div class="footer">
  <p>@sydney2018</p>
</div>




  </div>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<br>
<hr>
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Click to login</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">

      <div class="modal-body">

<%= flash[:error] %>
<div class="wrapper">

<%= form_tag login_path do %>


  <%= label_tag :email %>
  <%= email_field_tag :email, nil, :class => "form-control" %>

  <%= label_tag :password %>
  <%= password_field_tag :password, nil, :class => "form-control" %>
  <br>

  <%= submit_tag 'Login' %>


 </div>

<% end %>

</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <br>

app/views/transactions/_form.html.erb
<br>
<% if flash[:errors] %>
  <strong>Please correct the following errors:</strong>
  <ol>
  <% flash[:errors].each do |e| %>
    <li><%= e %></li>
  <% end %>
  </ol>
<% end %>

<%= form_for [@account, @transaction] do |f| %>



<fieldset>
  <%= f.label :from_account_id %>
  <%= f.select :from_account_id,
      @current_user.accounts.map { |a| [a.accountnumber, a.id]  },
      selected: ( params[:type] == 'from' ? @account.id : nil ),
      include_blank: true, :class => "form-control"
  %>
</fieldset>
<br>

<fieldset>
  <%= f.label :to_account_id %>
  <%= f.select :to_account_id, Account.includes(:user).order("users.name").map { |a| ["#{ a.user.name}: #{a.accountnumber}", a.id]  }, selected: ( params[:type] == 'to' ? @account.id : nil ), include_blank: true, :class => "form-control" %>
</fieldset>
<br>


<fieldset>
  <%= f.label :ammount %>
  <%= f.text_field :ammount, :class => "form-control" %>
</fieldset>

<fieldset>
  <%= f.label :description %>
  <%= f.text_field :description, :class => "form-control" %>
</fieldset>

<br>


  <%= f.submit %>

<% end %>

app/views/transactions/index.html.erb
<h2>Here is your Transactions</h2>

<h2>All Transactions</h2>

<ul>
  <% @transactions.each do |transaction| %>

    <li>
      <em><%= link_to transaction.ammount, transaction_path( transaction ) %></em>

      , <%= transaction.description %>
    </li>

  <% end %>
</ul>

app/views/transactions/new.html.erb
<%= render partial: 'form' %>

app/views/transactions/show.html.erb
<!--
<h4>Transaction History</h4>

<button class="btn" data-toggle="collapse" data-target="#demo">Transaction</button>
<div id="demo" class="collapse">
<hr>
<h5>From Transactions: </h5>


<% @account.from_transactions.each do |transaction| %>


<li>
  <p class="bg-info"> Transaction date:<%= transaction.date_opened %> Transaction Ammount: <%= transaction.ammount %> ,  Description: <%= transaction.description %> </p>
</li>
    <% end %>
    <hr>
    <%= column_chart @account.from_transactions.group(:ammount, :date_opened).count %>

<br>
<hr>
<h5>To Transactions: </h5>
<%#= line_chart Account.group_by_day(:created_at).count %>

<% @account.to_transactions.each do |transaction| %>

<li>
  <p class="bg-primary"> <%= transaction.date_opened %> , Transaction Ammount: <%= transaction.ammount %> ,  Description: <%= transaction.description %> </p>
</li>
    <% end %>
    <hr>
    <%= column_chart @account.to_transactions.group(:ammount, :date_opened).count %>
</div>
</div> -->

app/views/users/_form.html.erb
<% if flash[:errors] %>
  <strong>Please correct the following errors:</strong>
  <ol>
  <% flash[:errors].each do |e| %>
    <li><%= e %></li>
  <% end %>
  </ol>
<% end %>
<div class="form-group">
<%= form_for @user do |f| %>

<%= f.label :name %>
<%= f.text_field :name, :class => "form-control" %>
<br>
<%= f.label :email %>
<%= f.text_field :email, :class => "form-control" %>
<br>
<%= f.label :password %>
<%= f.password_field :password, :class => "form-control" %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, :class => "form-control" %>
<br>
<%= f.submit %>
</div>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<hr>


<h4>User Name: <%= @user.name %></h4>
<hr>
<br>


<%= link_to 'Personal Information', customer_path %>
<hr>
<p><strong>Accounts</strong>:</p>


<ul>
  <% @user.accounts.each do |account| %>
    <li>
      <%= link_to account.accountnumber, account %>
    </li>

  <% end %>

  
  <hr>
  <%= link_to 'Create New Account', new_account_path( @user ) %>
</ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>